name: Automated Release
description: Create a new release with an elegant release body.
author: oobook
branding:
  icon: target
  color: yellow
inputs:
  test:
    description: Run mode of the action
    required: false
<<<<<<< HEAD
    default: false
  gh_token:
=======
    default: 'false'
  gh-token:
>>>>>>> origin/dev
    description: GitHub token with repo access
    required: true
  tag:
    description: The tag of release
    required: false
  create:
<<<<<<< HEAD
    description: The release mode
    required: false
    default: true
  draft:
    description: Release the tag as draft
    required: false
    default: false
  prerelease:
    description: Release the tag as prerelease
    required: false
    default: false
=======
    description: 'The release mode'
    default: 'true'
  noCompatibles:
    description: 'Exclude uncompatible commits from the release notes'
    default: 'true'
>>>>>>> origin/dev
outputs:
  body:
    description: The release notes to use only text
  release-id:
    description: The generated release's id if create mode is true
  release-url:
    description: The generated release's url if create mode is true
runs:
  using: node20
  main: dist/index.js
