name: Automated Release
description: Create a new release with an elegant release body.
author: oobook
branding:
  icon: target
  color: yellow
inputs:
  gh_token:
    description: GitHub token with repo access
    required: true
  tag:
    description: The tag of release
    required: false
  test:
    description: Run mode of the action
    default: 'false'
  create:
    description: The release mode
  draft:
    description: Release the tag as draft
    default: 'false'
  prerelease:
    description: Release the tag as prerelease
    default: 'false'
  include-uncompatibles:
    description: 'Include uncompatible commits to the release notes'
    default: 'false'
outputs:
  body:
    description: The release notes to use only text
  release-id:
    description: The generated release's id if create mode is true
  release-url:
    description: The generated release's url if create mode is true
runs:
  using: node20
  main: dist/index.js